version: '3.8'
services:
  mysql:
        image: mysql
        container_name: mysql
        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=.rootpassword.
          - MYSQL_DATABASE=php-demo
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=.mysqlpassword
        ports:
          - "8082:3306"
  website:
    container_name: php-demo
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - "mysql:database"
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql      